{"message": "Running node", "node_id": "backwards_node_WjG0Skr5uY", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node_WjG0Skr5uY", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node_WjG0Skr5uY", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node_WjG0Skr5uY", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node_WjG0Skr5uY", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node_WjG0Skr5uY", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node_WjG0Skr5uY", "node_type": "BackwardsNode"}
{"message": "FakeException: An error occurred - This is a fake exception to simulate an error", "exc_info": "Traceback (most recent call last):\n  File \"/Users/matthew/git/logging_demo/src/base/base_node.py\", line 70, in run\n    raise FakeException(\"An error occurred\")\nbase.base_node.FakeException: FakeException: An error occurred - This is a fake exception to simulate an error", "node_id": "backwards_node_WjG0Skr5uY", "node_type": "BackwardsNode"}
{"message": "Stopping node", "node_id": "backwards_node_WjG0Skr5uY", "node_type": "BackwardsNode"}
{"message": "Running node", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "FakeException: An error occurred - This is a fake exception to simulate an error", "exc_info": "Traceback (most recent call last):\n  File \"/Users/matthew/git/logging_demo/src/base/base_node.py\", line 71, in run\n    raise FakeException(\"An error occurred\")\nbase.base_node.FakeException: FakeException: An error occurred - This is a fake exception to simulate an error", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Stopping node", "node_id": "backwards_node-PteOmtSVOK", "node_type": "BackwardsNode"}
{"message": "Running node", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-zQrOyOyeqe", "node_type": "BackwardsNode"}
{"message": "Running node", "node_id": "backwards_node-0qbe6wmt6J", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-0qbe6wmt6J", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-0qbe6wmt6J", "node_type": "BackwardsNode"}
{"message": "FakeException: An error occurred - This is a fake exception to simulate an error", "exc_info": "Traceback (most recent call last):\n  File \"/Users/matthew/git/logging_demo/src/base/base_node.py\", line 71, in run\n    raise FakeException(\"An error occurred\")\nbase.base_node.FakeException: FakeException: An error occurred - This is a fake exception to simulate an error", "node_id": "backwards_node-0qbe6wmt6J", "node_type": "BackwardsNode"}
{"message": "Stopping node", "node_id": "backwards_node-0qbe6wmt6J", "node_type": "BackwardsNode"}
{"message": "Running node", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "FakeException: An error occurred - This is a fake exception to simulate an error", "exc_info": "Traceback (most recent call last):\n  File \"/Users/matthew/git/logging_demo/src/base/base_node.py\", line 71, in run\n    raise FakeException(\"An error occurred\")\nbase.base_node.FakeException: FakeException: An error occurred - This is a fake exception to simulate an error", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Stopping node", "node_id": "backwards_node-ChUQs4FeXL", "node_type": "BackwardsNode"}
{"message": "Running node", "node_id": "backwards_node-XC3BwIqFkg", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-XC3BwIqFkg", "node_type": "BackwardsNode"}
{"message": "Running node", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "FakeException: An error occurred - This is a fake exception to simulate an error", "exc_info": "Traceback (most recent call last):\n  File \"/Users/matthew/git/logging_demo/src/base/base_node.py\", line 71, in run\n    raise FakeException(\"An error occurred\")\nbase.base_node.FakeException: FakeException: An error occurred - This is a fake exception to simulate an error", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Stopping node", "node_id": "backwards_node-RMmyfHP8Au", "node_type": "BackwardsNode"}
{"message": "Running node", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "FakeException: An error occurred - This is a fake exception to simulate an error", "exc_info": "Traceback (most recent call last):\n  File \"/Users/matthew/git/logging_demo/src/base/base_node.py\", line 67, in run\n    raise FakeException(\"An error occurred\")\nsrc.base.base_node.FakeException: FakeException: An error occurred - This is a fake exception to simulate an error", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "Stopping node", "node_id": "node-1736526094411448000", "node_type": "BaseNode"}
{"message": "Running node", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "FakeException: An error occurred - This is a fake exception to simulate an error", "exc_info": "Traceback (most recent call last):\n  File \"/Users/matthew/git/logging_demo/src/base/base_node.py\", line 67, in run\n    raise FakeException(\"An error occurred\")\nbase.base_node.FakeException: FakeException: An error occurred - This is a fake exception to simulate an error", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Stopping node", "node_id": "backwards_node-v57vmTA7ZK", "node_type": "BackwardsNode"}
{"message": "Running node", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526130874152000", "node_type": "BaseNode"}
{"message": "Running node", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "FakeException: An error occurred - This is a fake exception to simulate an error", "exc_info": "Traceback (most recent call last):\n  File \"/Users/matthew/git/logging_demo/src/base/base_node.py\", line 67, in run\n    raise FakeException(\"An error occurred\")\nbase.base_node.FakeException: FakeException: An error occurred - This is a fake exception to simulate an error", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Stopping node", "node_id": "backwards_node-yS7UnYtnpQ", "node_type": "BackwardsNode"}
{"message": "Running node", "node_id": "backwards_node-sl0zaOboeZ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-sl0zaOboeZ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-sl0zaOboeZ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-sl0zaOboeZ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-sl0zaOboeZ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-sl0zaOboeZ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-sl0zaOboeZ", "node_type": "BackwardsNode"}
{"message": "Node continues to run", "node_id": "backwards_node-sl0zaOboeZ", "node_type": "BackwardsNode"}
{"message": "Running node", "node_id": "node-1736526494400931000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526494400931000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526494400931000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526494400931000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526494400931000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526494400931000", "node_type": "BaseNode"}
{"message": "Node continues to run", "node_id": "node-1736526494400931000", "node_type": "BaseNode"}
{"message": "FakeException: An error occurred - This is a fake exception to simulate an error", "exc_info": "Traceback (most recent call last):\n  File \"/Users/matthew/git/logging_demo/src/base/base_node.py\", line 74, in run\n    raise FakeException(\"An error occurred\")\nsrc.base.base_node.FakeException: FakeException: An error occurred - This is a fake exception to simulate an error", "node_id": "node-1736526494400931000", "node_type": "BaseNode"}
{"message": "Stopping node", "node_id": "node-1736526494400931000", "node_type": "BaseNode"}
